on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - id: version
        name: Get project version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Test and build inside dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test release HANDYPROXY_VERSION=${{ steps.version.outputs.VERSION }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: handyproxy
