on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: version
      name: Get version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        ldflags: -X main.version=${{ steps.version.outputs.VERSION }}
